{% set version = "0.8.0.3126" %}
{% set lib_version = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2]+".0" %}
{% set soname = version.split(".")[0] %}
{% set arm_variant_type = arm_variant_type | default("sbsa") %}
{% set cuda_compiler_version = cuda_compiler_version | default("None") %}

package:
  name: libcusolvermp-split
  version: {{ version }}

source:
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-x86_64/libcusolvermp-linux-x86_64-{{ version }}_cuda12-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
    sha256: "3215039d5e5ab2a2c47b53e15f0dbc2341bd757a747e5400a049008a3dd65883"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("12")]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-x86_64/libcusolvermp-linux-x86_64-{{ version }}_cuda13-archive.tar.xz"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
    sha256: "9cc471e19cd1593bc5dd95dca3cd0b444c1bb206293550f15e3b3a202d3441f5"  # [linux and x86_64 and (cuda_compiler_version or "").startswith("13")]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-sbsa/libcusolvermp-linux-sbsa-{{ version }}_cuda12-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
    sha256: "e84a24fd6448e97a1d8574bda190aa623c24bddb088f5aab1ab7aecda6297e3f"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("12") and arm_variant_type == "sbsa"]
  - url: "https://developer.download.nvidia.com/compute/cusolvermp/redist/libcusolvermp/linux-sbsa/libcusolvermp-linux-sbsa-{{ version }}_cuda13-archive.tar.xz"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]
    sha256: "100fa8918b609bf1beb194526a45994b56dde662659dfbc98e183df97be1217f"  # [linux and aarch64 and (cuda_compiler_version or "").startswith("13") and arm_variant_type == "sbsa"]

build:
  number: 0
  skip: true  # [not (linux64 or aarch64)]
  skip: true  # [cuda_compiler_version in (None, "None") or (cuda_compiler_version or "").startswith("11")]
  script:
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX
    - check-glibc "$PREFIX"/lib*/*.so.* "$PREFIX"/bin/* "$PREFIX"/targets/*/lib*/*.so.* "$PREFIX"/targets/*/bin/*  # [linux]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]

outputs:
  - name: libcusolvermp{{ soname }}
    build:
      missing_dso_whitelist:
        - "*/libcuda.so.*"  # nvidia drivers
      run_exports:
        - {{ pin_subpackage("libcusolvermp" ~ soname, max_pin="x.x") }}
      ignore_run_exports_from:
        - cuda-cudart-dev
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        - libnvjitlink-dev
      ignore_run_exports:
        # Ignore `cuda-version` constraint as this supports CUDA Enhanced Compatibility.
        - cuda-version
    files:
      - lib/libcusolverMp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64]
      host:
        - cuda-version {{ cuda_compiler_version }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
        - libnvjitlink-dev
        - nccl 2.25.*  # [(cuda_compiler_version or "").startswith("12")]
        - nccl 2.27.*  # [(cuda_compiler_version or "").startswith("13")]
      run:
        - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
        - cuda-cudart
        - libcublas
        - libcusolver
        - libcusparse
        - libnvjitlink
    test:
      commands:
        - test -L $PREFIX/lib/libcusolverMp.so.{{ soname }}
        - test -f $PREFIX/lib/libcusolverMp.so.{{ lib_version }}

  - name: libcusolvermp-dev
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
        - {{ pin_subpackage("libcusolvermp" ~ soname, max_pin="x.x") }}
    files:
      - lib/libcusolverMp.so
      - include/cusolverMp.h
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [linux and aarch64]
      run:
        - {{ pin_subpackage("libcusolvermp" ~ soname, exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/cusolverMp.h
        - test -L $PREFIX/lib/libcusolverMp.so

about:
  home: https://docs.nvidia.com/cuda/cusolvermp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cusolvermp/license/index.html
  summary: NVIDIA cuSOLVERMp is a high-performance, distributed-memory, GPU-accelerated library that provides tools for the solution of dense linear systems and eigenvalue problems.
  description: |
    NVIDIA cuSOLVERMp is a high-performance, distributed-memory, GPU-accelerated library that provides tools for the solution of dense linear systems and eigenvalue problems.
    cuSOLVERMp is compatible with 2D block-cyclic data layout and provides ScaLAPACK-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cusolvermp/

extra:
  feedstock-name: libcusolvermp
  recipe-maintainers:
    - mrogowski
    - conda-forge/cuda
